.TH 4dtris 6 "2011.02.13" "0.4.2"
.SH NAME
4dtris - Tetris in four dimensions
.SH SYNOPSIS
4dtris
.SH DESCRIPTION
4D-TRIS is an alteration of the well-known Tetris game. The game field is 
extended to 4D space, which has to filled up by the gamer with 4D hyper cubes. 
The software is written in C with OpenGL and SDL.

For usage see in-game help page.

Project web page: http://sourceforge.net/apps/wordpress/dtris/
.SH OPTIONS

.SH BUGS

Please report bugs here: https://bugs.launchpad.net/4dtris

.SH AUTHOR

Laszlo Simon <laszlo.simon@gmail.com>

.SH SEE ALSO