.TH ntris 6 "2013.04.19" "1.0.0"
.SH NAME
ntris - Tetris in four dimensions
.SH SYNOPSIS
ntris
.SH DESCRIPTION
N-TRIS is an alteration of the well-known Tetris game. The game field is
extended to n-dimensional space, which has to filled up by the gamer with N-D hyper cubes.
The software is written in C with OpenGL and SDL.

For usage see in-game help page.

Project web page: https://github.com/frony0/ntris
.SH OPTIONS

.SH BUGS

Please report bugs here: https://github.com/frony0/ntris/issues

.SH AUTHOR

Tony Olagbaiye <frony0@gmail.com>

.SH SEE ALSO
